### PR TITLE
[leaks] Properly free bits and cnt on shrinkingset destruction.

### PR DESCRIPTION
**Pull request by kallewoof**

### CODE REVIEW

**Comment by tromp** [comment]
free memory on destruction, as suggested by kallewoof

**Comment by kallewoof** [comment]
Did you mean to close without merging?

**Comment by tromp** [comment]
still getting used to git:-)

**Comment by kallewoof** [comment]
Haha sorry I didn't realize you literally just closed it. I thought the comment was an hour ago

**Pull request merged**
